#!/bin/bash

run_test() {
  test_dirname "a/bc/d" "a/bc"
  test_dirname "//////////a/bc/" "//////////a"
  test_dirname "/a/bc//" "/a"
  test_dirname "a/bc///d////あ" "a/bc///d"
}

test_dirname() {
  if assert_equal "$(dirname.bash "$1")" "$2"; then
    log_succ "test_dirname: $1"
  else
    log_err "test_dirname: $1"
  fi
}

run_test "$@"
