#!/bin/bash

TRUE=0
FALSE=1

test_is_alphabet() {
  local case="$1"
  local str="$3"
  local expected="$2"
  local actual

  if is_alphabet "$str"; then
    actual="$TRUE"
  else
    actual="$FALSE"
  fi

  if assert_equal "$actual" "$expected"; then
    log_succ "test_is_alphabet $case"
  else
    log_err "test_is_alphabet $case"
  fi
}

run_test() {
  test_is_alphabet "case alphabet" "$TRUE" "abcdefg"
  test_is_alphabet "case upperCase alphabet" "$TRUE" "AAAAAfg"
  test_is_alphabet "case bool string" "$TRUE" "true"
  test_is_alphabet "case alphabet with space" "$FALSE" "abc dfeg"
  test_is_alphabet "case number" "$FALSE" "12"
  test_is_alphabet "case emoji" "$FALSE" "🐳"
}

run_test "$@"
