#!/bin/bash

TRUE=0
FALSE=1

test_is_arr_contains() {
  local case
  local element
  local expected
  local actual

  case="$1" && expected="$2" && element="$3" && shift && shift && shift
  if is_arr_contains "$element" "$@"; then
    actual="$TRUE"
  else
    actual="$FALSE"
  fi

  if assert_equal "$actual" "$expected"; then
    log_succ "test_is_arr_contains $case"
  else
    log_err "test_is_arr_contains $case"
  fi
}

run_test() {
  arr=("a" "b" "c")
  test_is_arr_contains "case string contains" "$TRUE" "b" "${arr[@]}"

  arr=("a" "b" "c")
  test_is_arr_contains "case string not contains" "$FALSE" "d" "${arr[@]}"

  arr=(true false true)
  test_is_arr_contains "case bool contains" "$TRUE" false "${arr[@]}"

  arr=(true true true)
  test_is_arr_contains "case bool not contains" "$FALSE" false "${arr[@]}"

  arr=()
  test_is_arr_contains "case empty not contains" "$FALSE" "" "${arr[@]}"
}

run_test "$@"
