#!/bin/bash

TRUE=0
FALSE=1

test_is_empty_string() {
  local case="$1"
  local str="$3"
  local expected="$2"
  local actual

  if is_empty_string "$str"; then
    actual="$TRUE"
  else
    actual="$FALSE"
  fi

  if assert_equal "$actual" "$expected"; then
    log_succ "test_is_empty_string $case"
  else
    log_err "test_is_empty_string $case"
  fi
}

run_test() {
  test_is_empty_string "case empty string" "$TRUE" ""
  test_is_empty_string "case not empty string" "$FALSE" "AAAAAfg"
}

run_test "$@"
