#!/bin/bash

TRUE=0
FALSE=1

test_is_pipe() {
  local actual
  local this="${FUNCNAME[0]}"

  if is_pipe; then
    actual="$TRUE"
  else
    actual="$FALSE"
  fi

  if [[ -z "$1" ]]; then
    test_err "first argument is required"
  fi

  if assert_equal "$actual" "$1"; then
    log_succ "$this $2"
  else
    log_err "$this $2" "$this"

    printf "\t%s\n" "$this: expected: $1"
    printf "\t%s\n" "$this: actual:   $actual"
  fi
}

run_test() {
  printf "no name pipe input" | test_is_pipe "$TRUE" "case no name pipe"
  echo "stdin process substitution" > >(test_is_pipe "$TRUE")
  test_is_pipe "$TRUE" "case stdin process substitution" < <(printf "stdin process substitution\n")
  cat <(test_is_pipe "$TRUE" "case stdout process substitution")
  test_is_pipe "$TRUE" "case stdout process substitution 2" | cat -
}

run_test "$@"
