#!/bin/bash

TRUE=0
FALSE=1

test_is_str_contains() {
  local case="$1"
  local str="$4"
  local src="$3"
  local expected="$2"
  local actual

  if is_str_contains "$src" "$str"; then
    actual="$TRUE"
  else
    actual="$FALSE"
  fi

  if assert_equal "$actual" "$expected"; then
    log_succ "test_is_str_contains $case"
  else
    log_err "test_is_str_contains $case"
  fi
}

run_test() {
  test_is_str_contains "case string contains" "$TRUE" "adfstrsdf" "str"
  test_is_str_contains "case string contains suffix" "$TRUE" "adf str" "str"
  test_is_str_contains "case string contains prefix" "$TRUE" "str adf" "str"
  test_is_str_contains "case string not contains" "$FALSE" "aaa" "b"
  test_is_str_contains "case string empty" "$FALSE" "" ""
  test_is_str_contains "case string contains space" "$TRUE" "     " " "
}

run_test "$@"
