#!/bin/bash

readonly cf="\\033[0m"
readonly red="\\033[0;31m"

readonly BIN_SCRIPTS="$BIN_SCRIPTS"
BIN_SCRIPTS_BIN_EXTERNAL=""

log_err() {
  echo -e "${red}❌${cf} $1" 1>&2
}

is_err() {
  if [[ $? -gt 0 ]]; then
    return 0
  else
    return 1
  fi
}

is_exists_command() {
  which "$1" >/dev/null 2>&1
  return $?
}

err_exit() {
  log_err "$1"
  if [[ -z "$2" ]]; then
    exit 1
  else
    exit "$2"
  fi
}

install_tfref() {
  curl -s https://raw.githubusercontent.com/kis9a/tfref/main/tfref >"$BIN_SCRIPTS_BIN_EXTERNAL/tfref"
  chmod +x "$BIN_SCRIPTS_BIN_EXTERNAL/tfref"
}

install_runeboxes() {
  curl -s https://raw.githubusercontent.com/kis9a/runeboxes/main/runeboxes >"$BIN_SCRIPTS_BIN_EXTERNAL/runeboxes"
  chmod +x "$BIN_SCRIPTS_BIN_EXTERNAL/runeboxes"
}

install_runeflex() {
  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflex >"$BIN_SCRIPTS_BIN_EXTERNAL/runeflex"
  chmod +x "$BIN_SCRIPTS_BIN_EXTERNAL/runeflex"
}

install_runeflexrn() {
  curl -s https://raw.githubusercontent.com/kis9a/runeflex/main/runeflexrn >"$BIN_SCRIPTS_BIN_EXTERNAL/runeflexrn"
  chmod +x "$BIN_SCRIPTS_BIN_EXTERNAL/runeflexrn"
}

if [[ -z "$BIN_SCRIPTS" ]]; then
  err_exit "\$BIN_SCRIPTS is not found"
else
  BIN_SCRIPTS_BIN_EXTERNAL="$BIN_SCRIPTS/bin/external"
  if [[ ! -d "$BIN_SCRIPTS_BIN_EXTERNAL" ]]; then
    mkdir -p "$BIN_SCRIPTS_BIN_EXTERNAL"
    if is_err; then
      err_exit "can't create directory \$BIN_SCRIPTS_BIN_EXTERNAL"
    fi
  fi
fi

if ! is_exists_command "curl"; then
  err_exit "curl command is not found" >&2
fi

if ! is_exists_command "tfref"; then
  install_tfref
fi

if ! is_exists_command "runeboxes"; then
  install_runeboxes
fi

if ! is_exists_command "runeflex"; then
  install_runeflex
fi

if ! is_exists_command "runeflexrn"; then
  install_runeflexrn
fi
